In [4]:
import numpy as np
k=np.array([1,2,3,4,5,1])
print(k)

[1 2 3 4 5 1]


In [5]:
print(np.arange(10,1000,10))   #start=10, end(excluding),increment

[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180
 190 200 210 220 230 240 250 260 270 280 290 300 310 320 330 340 350 360
 370 380 390 400 410 420 430 440 450 460 470 480 490 500 510 520 530 540
 550 560 570 580 590 600 610 620 630 640 650 660 670 680 690 700 710 720
 730 740 750 760 770 780 790 800 810 820 830 840 850 860 870 880 890 900
 910 920 930 940 950 960 970 980 990]


In [7]:
print(np.shape(k))

(6,)


In [8]:
print(np.ndim(k))

1


In [13]:
print(np.linspace(1,0,10))
print(np.linspace(0,1,10))

[1.         0.88888889 0.77777778 0.66666667 0.55555556 0.44444444
 0.33333333 0.22222222 0.11111111 0.        ]


In [14]:
a=np.ones((5,3))
print(a)
print(np.ndim(a))
print(np.shape(a))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
2
(5, 3)


In [16]:
b=np.zeros((5,3))
print(b)
print(np.ndim(b))
print(np.shape(b))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2
(5, 3)


In [21]:
c=np.eye(5)
print(c)
print(np.ndim(c))
print(np.shape(c))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
2
(5, 5)


In [22]:
d=np.diag([1,2,3,5,1])
print(d)
print(np.ndim(d))
print(np.shape(d))

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 1]]
2
(5, 5)


In [23]:
e=np.random.rand(10)
print(e)

[0.62888786 0.31328055 0.52856524 0.34094562 0.91444538 0.16624355
 0.86166503 0.72245977 0.32662198 0.71641678]


In [28]:
f=[5+2j,2+9j,6+1j]
print(f)

[(5+2j), (2+9j), (6+1j)]


In [30]:
d[2,2]=11
print(d)

[[ 1  0  0  0  0]
 [ 0  2  0  0  0]
 [ 0  0 11  0  0]
 [ 0  0  0  5  0]
 [ 0  0  0  0  1]]


In [35]:
list1=np.arange(10);
print(list1)
list2=list1[::2]
print(list2)
list2[1]=11
print(list2)
print(list1)


[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[ 0 11  4  6  8]
[ 0  1 11  3  4  5  6  7  8  9]


In [36]:
list1=np.arange(10);
print(list1)
list2=list1[::2].copy()
print(list2)
list2[1]=11
print(list2)
print(list1)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[ 0 11  4  6  8]
[0 1 2 3 4 5 6 7 8 9]


In [6]:
g=np.random.randint(0,20,15)
print(g)
g[[1,2,3,4,5,6]]

[14 16  1  6 10  2  3 16 19  2  5  2 18  8  3]


array([16,  1,  6, 10,  2,  3])

In [39]:
print(np.ndim(g))
print(np.shape(g))

1
(15,)


In [45]:
mask=(g%2==0)     #name shoule be same as the list to which condition is applied later
extracted=g[mask]
print(mask)
print(extracted)
g[mask]=-1
print(g)

[False False False False False False False False False False False False
 False False False]
[]
[-1 -1 -1  7 -1 -1 -1 -1 -1 13 -1  5 11 -1  3]


In [8]:
a=[1,2,3,4]
b=[1,2,3,5]
np.array_equal(a,b);
np.logical_or(a,b);
np.logical_and(a,b);

In [ ]:
#functions on numpy array, gets executed on all ele
np.sin(a)
np.log(a)
np.exp(a)
np.sum(a)

